"""Todoist client — the system's task store and its memory.

Todoist is deliberately the state layer. Matt completes a task when he
does the work, so the open-task list alone answers everything the weekly
loop needs:

- a marked task exists and isn't overdue  -> tracked, nothing to do
- a marked task exists and IS overdue     -> he didn't do it; review it
- no marked task for an actionable item   -> create one
- a task vanishes from the open list      -> it was completed

That last line is why this module never touches the completed-tasks
endpoint. Absence *is* the completion signal. The one thing it cannot
recover is *when* something was done, which is what label retreatment
intervals and annual caps would need — that is a later change, and it is
the only reason to reach for completed tasks at all.

**Ownership.** The lawn project is mixed-use: mower servicing, azaleas,
oak spikes, and hand-written lawn notes all live alongside anything this
creates. So generated tasks carry a visible marker in the title —
`Fall pre-emergent [preemergent-fall/2026]` — and de-duplication matches
that marker exactly. No fuzzy title matching, which means a hand-written
"Apply Pre Emergnent" is never mistaken for a generated one, and nothing
the user wrote is ever modified.

The marker carries the occurrence year because program items recur: the
2026 fall pre-emergent and the 2027 one are different tasks.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date
from typing import TYPE_CHECKING, Any

import httpx

from lawn_agents.logging import get_logger

if TYPE_CHECKING:
    from lawn_agents.config import AppConfig

log = get_logger(__name__)

API_BASE = "https://api.todoist.com/api/v1"
OWNED_LABEL = "lawn-agents"

_MARKER_RE = re.compile(r"\[([a-z0-9][a-z0-9-]*)/(\d{4})\]\s*$")


def marker(item_id: str, year: int) -> str:
    """Render the title suffix that identifies a generated task."""
    return f"[{item_id}/{year}]"


def parse_marker(title: str) -> tuple[str, int] | None:
    """Extract `(item_id, year)` from a task title, or None if unmarked."""
    match = _MARKER_RE.search(title.strip())
    if match is None:
        return None
    return match.group(1), int(match.group(2))


@dataclass(slots=True, frozen=True)
class Task:
    """An open Todoist task, plus whatever we can tell about ownership."""

    id: str
    content: str
    description: str
    due: date | None
    labels: tuple[str, ...]
    item_id: str | None
    """Program item this task tracks, if it carries our marker."""

    year: int | None

    @property
    def owned(self) -> bool:
        """True when this task was generated by lawn-agents."""
        return self.item_id is not None

    def is_overdue(self, today: date) -> bool:
        """True when the task has a due date already in the past.

        An open, overdue task means the work didn't happen — completing
        it is what makes it disappear from this list.
        """
        return self.due is not None and self.due < today


class TodoistError(RuntimeError):
    """Any failure talking to Todoist."""


class TodoistClient:
    """Thin wrapper over the Todoist REST surface we actually use.

    Deliberately small: list open tasks in one project, create a task,
    close a task. Everything clever lives in the caller.
    """

    def __init__(self, token: str, project_id: str, *, client: httpx.Client | None = None) -> None:
        """Build a client.

        Args:
            token: Todoist API token.
            project_id: The project generated tasks live in.
            client: Optional injected `httpx.Client` (tests pass a
                `MockTransport`-backed one).
        """
        self._project_id = project_id
        self._owns_client = client is None
        self._client = client or httpx.Client(
            base_url=API_BASE,
            timeout=30.0,
            headers={"Authorization": f"Bearer {token}"},
        )

    def __enter__(self) -> TodoistClient:
        """Enter the context manager."""
        return self

    def __exit__(self, *exc: object) -> None:
        """Close the HTTP client on exit."""
        self.close()

    def close(self) -> None:
        """Close the HTTP client, unless it was injected by the caller."""
        if self._owns_client:
            self._client.close()

    # --- reads ---

    def open_tasks(self) -> list[Task]:
        """Every open task in the configured project.

        Completed tasks are absent by construction — that absence is how
        the loop knows work got done.
        """
        try:
            response = self._client.get(
                "/tasks", params={"project_id": self._project_id, "limit": 200}
            )
            response.raise_for_status()
        except httpx.HTTPError as exc:
            msg = f"could not list Todoist tasks: {exc}"
            raise TodoistError(msg) from exc

        payload: Any = response.json()
        rows = payload.get("results", payload) if isinstance(payload, dict) else payload
        tasks = [_to_task(row) for row in rows]
        log.info(
            "todoist.open_tasks",
            total=len(tasks),
            owned=sum(1 for t in tasks if t.owned),
        )
        return tasks

    # --- writes ---

    def create_task(
        self,
        *,
        content: str,
        description: str = "",
        due: date | None = None,
        labels: list[str] | None = None,
    ) -> Task:
        """Create a task in the configured project."""
        body: dict[str, Any] = {
            "content": content,
            "project_id": self._project_id,
            "description": description,
            "labels": labels if labels is not None else [OWNED_LABEL],
        }
        if due is not None:
            body["due_date"] = due.isoformat()

        try:
            response = self._client.post("/tasks", json=body)
            response.raise_for_status()
        except httpx.HTTPError as exc:
            msg = f"could not create Todoist task {content!r}: {exc}"
            raise TodoistError(msg) from exc

        task = _to_task(response.json())
        log.info("todoist.task_created", task_id=task.id, content=task.content)
        return task

    def update_task(
        self,
        task_id: str,
        *,
        content: str | None = None,
        description: str | None = None,
        due: date | None = None,
    ) -> None:
        """Update fields on an existing task.

        Only ever called against tasks this system created — identified
        by their title marker. Hand-written tasks are left alone.
        """
        body: dict[str, Any] = {}
        if content is not None:
            body["content"] = content
        if description is not None:
            body["description"] = description
        if due is not None:
            body["due_date"] = due.isoformat()
        if not body:
            return
        try:
            response = self._client.post(f"/tasks/{task_id}", json=body)
            response.raise_for_status()
        except httpx.HTTPError as exc:
            msg = f"could not update Todoist task {task_id}: {exc}"
            raise TodoistError(msg) from exc
        log.info("todoist.task_updated", task_id=task_id, fields=sorted(body))

    def delete_task(self, task_id: str) -> None:
        """Delete a task outright.

        Distinct from `close_task` on purpose. Completion is this
        system's record that work happened; closing a task that was never
        done would poison exactly the signal the weekly loop reads. Tasks
        being retired — superseded, abandoned, no longer relevant — get
        deleted instead.
        """
        try:
            response = self._client.delete(f"/tasks/{task_id}")
            response.raise_for_status()
        except httpx.HTTPError as exc:
            msg = f"could not delete Todoist task {task_id}: {exc}"
            raise TodoistError(msg) from exc
        log.info("todoist.task_deleted", task_id=task_id)

    def close_task(self, task_id: str) -> None:
        """Mark a task complete."""
        try:
            response = self._client.post(f"/tasks/{task_id}/close")
            response.raise_for_status()
        except httpx.HTTPError as exc:
            msg = f"could not close Todoist task {task_id}: {exc}"
            raise TodoistError(msg) from exc
        log.info("todoist.task_closed", task_id=task_id)


def build_client(config: AppConfig, token: str) -> TodoistClient:
    """Construct a client from config, or raise if Todoist isn't configured."""
    if not config.todoist.project_id:
        msg = "todoist.project_id is not set in config.yaml"
        raise TodoistError(msg)
    return TodoistClient(token, config.todoist.project_id)


# --- internals ------------------------------------------------------------


def _to_task(row: dict[str, Any]) -> Task:
    content = str(row.get("content") or "")
    parsed = parse_marker(content)
    due_raw = (row.get("due") or {}).get("date") if isinstance(row.get("due"), dict) else None
    return Task(
        id=str(row.get("id") or ""),
        content=content,
        description=str(row.get("description") or ""),
        # Todoist returns date-only for all-day tasks and a datetime for
        # timed ones; we only care about the day.
        due=date.fromisoformat(due_raw[:10]) if isinstance(due_raw, str) and due_raw else None,
        labels=tuple(row.get("labels") or ()),
        item_id=parsed[0] if parsed else None,
        year=parsed[1] if parsed else None,
    )
